name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Streamlit app
      run: |
        # Basic import test
        python -c "import streamlit; import pandas; import plotly; print('All imports successful')"
        
        # Check if app.py runs without errors
        timeout 30 streamlit run app.py --server.headless true --server.port 8502 &
        sleep 10
        curl -f http://localhost:8502 || exit 1
